In [0]:
import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers

In [0]:
tf.enable_eager_execution()

In [0]:
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

x_data = np.array([[h]], dtype=np.float32)
hidden_size = 2

In [0]:
cell = layers.SimpleRNNCell(units=hidden_size)
rnn = layers.RNN(cell, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

In [0]:
print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[-0.66346055  0.39231372]]], shape: (1, 1, 2)
states: [[-0.66346055  0.39231372]], shape: (1, 2)


In [0]:
x_data = np.array([[
    [1., 0., 0., 0.],
    [0., 1., 0., 0.],
    [0., 0., 1., 0.],
    [0., 0., 1., 0.],
    [0., 0., 0., 1.]]])
print(x_data.shape)
# or

x_data = np.array([[h, e, l, l, o]], dtype = np.float32)
hidden_size = 2

(1, 5, 4)


In [0]:
rnn = layers.SimpleRNN(hidden_size, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape: (1, 5, 4)
outputs: [[[-0.25932392 -0.41902524]
  [ 0.40711668  0.438779  ]
  [ 0.7263851   0.78510183]
  [ 0.8662173   0.8649097 ]
  [ 0.6254981  -0.06451443]]], shape: (1, 5, 2)
states: [[ 0.6254981  -0.06451443]], shape: (1, 2)


In [0]:
x_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype = np.float32)
hidden_size = 2


rnn = layers.SimpleRNN(hidden_size, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape: (3, 5, 4)
outputs: [[[ 0.72884125 -0.7150932 ]
  [-0.51186204  0.5121509 ]
  [ 0.02792472 -0.3290405 ]
  [-0.74885786 -0.28461024]
  [ 0.13648716  0.49667472]]

 [[ 0.41378027  0.63138646]
  [ 0.2049407  -0.73225105]
  [-0.88565403 -0.19991682]
  [-0.3227304   0.3592875 ]
  [-0.20346777 -0.38588193]]

 [[-0.59557456 -0.43093145]
  [-0.5987635   0.2674077 ]
  [ 0.7639265   0.79166687]
  [ 0.5655997  -0.32563236]
  [-0.8564359  -0.62452656]]], shape: (3, 5, 2)
states: [[ 0.13648716  0.49667472]
 [-0.20346777 -0.38588193]
 [-0.8564359  -0.62452656]], shape: (3, 2)
