In [0]:
# Lab 4 Multi-variable linear regression
# https://www.tensorflow.org/programmers_guide/reading_data

import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

# Step 1
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

# Step 2
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Step 3
# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
Use tf.cast instead.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLin

In [0]:
# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

writer = tf.summary.FileWriter('TF_board_example')
writer.add_graph(tf.get_default_graph())
writer.flush()

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

sess.close()

0 Cost:  66493.49 
Prediction:
 [[ -97.77742 ]
 [-104.20064 ]
 [ -73.790184]
 [ -80.69573 ]
 [ -83.424805]
 [ -77.125984]
 [ -96.58483 ]
 [ -97.077934]
 [ -98.0645  ]
 [ -98.20872 ]]
10 Cost:  58.482735 
Prediction:
 [[183.33313]
 [179.31087]
 [143.76825]
 [149.65692]
 [179.38904]
 [144.97615]
 [151.85503]
 [192.5734 ]
 [138.19394]
 [177.08173]]
20 Cost:  64.24926 
Prediction:
 [[184.99916]
 [180.82239]
 [145.17894]
 [151.01866]
 [181.27592]
 [146.55818]
 [153.32072]
 [194.40608]
 [139.69795]
 [178.84953]]
30 Cost:  63.77939 
Prediction:
 [[184.96532]
 [180.75945]
 [145.18205]
 [150.99251]
 [181.31123]
 [146.60094]
 [153.31879]
 [194.39308]
 [139.73596]
 [178.8641 ]]
40 Cost:  63.25396 
Prediction:
 [[184.92007]
 [180.6861 ]
 [145.1756 ]
 [150.95703]
 [181.3338 ]
 [146.63304]
 [153.30688]
 [194.36755]
 [139.76381]
 [178.8667 ]]
50 Cost:  62.73286 
Prediction:
 [[184.87494]
 [180.61302]
 [145.16911]
 [150.92165]
 [181.35616]
 [146.66493]
 [153.29498]
 [194.34206]
 [139.79146]
 [178.8692

550 Cost:  41.868813 
Prediction:
 [[182.85085]
 [177.34868]
 [144.88284]
 [149.33836]
 [182.34924]
 [148.07663]
 [152.77489]
 [193.19893]
 [141.00383]
 [179.00607]]
560 Cost:  41.540276 
Prediction:
 [[182.81467]
 [177.2906 ]
 [144.8778 ]
 [149.31013]
 [182.36679]
 [148.10149]
 [152.76587]
 [193.1785 ]
 [141.02495]
 [179.00896]]
570 Cost:  41.214653 
Prediction:
 [[182.77866]
 [177.23277]
 [144.87282]
 [149.28204]
 [182.38425]
 [148.12625]
 [152.7569 ]
 [193.15817]
 [141.04596]
 [179.01187]]
580 Cost:  40.891914 
Prediction:
 [[182.74278]
 [177.17522]
 [144.86783]
 [149.25406]
 [182.40164]
 [148.15088]
 [152.74796]
 [193.13791]
 [141.06686]
 [179.01477]]
590 Cost:  40.5721 
Prediction:
 [[182.70705]
 [177.11792]
 [144.86288]
 [149.2262 ]
 [182.41895]
 [148.17538]
 [152.73907]
 [193.11772]
 [141.08765]
 [179.01767]]
600 Cost:  40.255287 
Prediction:
 [[182.67151]
 [177.0609 ]
 [144.85797]
 [149.19849]
 [182.43617]
 [148.1998 ]
 [152.73027]
 [193.09769]
 [141.10834]
 [179.02061]]
610 Co

1130 Cost:  26.963852 
Prediction:
 [[180.9903 ]
 [174.3772 ]
 [144.62962]
 [147.89091]
 [183.24078]
 [149.33559]
 [152.32616]
 [192.1486 ]
 [142.05952]
 [179.18054]]
1140 Cost:  26.769077 
Prediction:
 [[180.96211]
 [174.33244]
 [144.62587]
 [147.86906]
 [183.2541 ]
 [149.3543 ]
 [152.31964]
 [192.13272]
 [142.07497]
 [179.18364]]
1150 Cost:  26.576061 
Prediction:
 [[180.93405]
 [174.2879 ]
 [144.62215]
 [147.8473 ]
 [183.26733]
 [149.37291]
 [152.31314]
 [192.11688]
 [142.09033]
 [179.18672]]
1160 Cost:  26.384872 
Prediction:
 [[180.90613]
 [174.24359]
 [144.61845]
 [147.82565]
 [183.28053]
 [149.39145]
 [152.3067 ]
 [192.1011 ]
 [142.10562]
 [179.18982]]
1170 Cost:  26.195236 
Prediction:
 [[180.8783 ]
 [174.19943]
 [144.61476]
 [147.8041 ]
 [183.29364]
 [149.4099 ]
 [152.30028]
 [192.08542]
 [142.12083]
 [179.19292]]
1180 Cost:  26.00737 
Prediction:
 [[180.8506 ]
 [174.15549]
 [144.6111 ]
 [147.78262]
 [183.3067 ]
 [149.42825]
 [152.2939 ]
 [192.0698 ]
 [142.13596]
 [179.19601]]

1650 Cost:  18.839018 
Prediction:
 [[179.67387]
 [172.29776]
 [144.45831]
 [146.87305]
 [183.8548 ]
 [150.1958 ]
 [152.03186]
 [191.40587]
 [142.76007]
 [179.34247]]
1660 Cost:  18.716946 
Prediction:
 [[179.65132]
 [172.26231]
 [144.45543]
 [146.85565]
 [183.86516]
 [150.21025]
 [152.02701]
 [191.39313]
 [142.77165]
 [179.34558]]
1670 Cost:  18.596016 
Prediction:
 [[179.62885]
 [172.22705]
 [144.45259]
 [146.83835]
 [183.87547]
 [150.22464]
 [152.0222 ]
 [191.38046]
 [142.78317]
 [179.34871]]
1680 Cost:  18.476154 
Prediction:
 [[179.60648]
 [172.19194]
 [144.44975]
 [146.8211 ]
 [183.88573]
 [150.23897]
 [152.01741]
 [191.36784]
 [142.79462]
 [179.35182]]
1690 Cost:  18.357405 
Prediction:
 [[179.58421]
 [172.157  ]
 [144.44693]
 [146.80396]
 [183.89595]
 [150.25322]
 [152.01268]
 [191.3553 ]
 [142.80602]
 [179.35495]]
1700 Cost:  18.23969 
Prediction:
 [[179.56204]
 [172.12221]
 [144.44412]
 [146.78687]
 [183.90613]
 [150.26738]
 [152.00795]
 [191.34279]
 [142.81734]
 [179.35808]]