In [33]:
import numpy as np
import tensorflow as tf

tf.set_random_seed(777)

In [34]:
xy = np.loadtxt("data-01-test-score.csv", delimiter=',', dtype=np.float32)

In [35]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [36]:
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data, len(y_data))

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 25


In [37]:
# Placeholders for a tensor that will be always fed.
x = tf.placeholder(tf.float32, shape=[None, 3])
y = tf.placeholder(tf.float32, shape=[None, 1])

w = tf.Variable(tf.random_normal([3, 1]), name = "weight")
b = tf.Variable(tf.random_normal([1]), name = "bias")

In [38]:
# Hypothesis
hypothesis = tf.matmul(x, w) + b

In [39]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - y))

In [40]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [41]:
# Launch the graph in a session
sess = tf.Session()

# Initialise global variables in the graph
sess.run(tf.global_variables_initializer())
    
# Set up feed_dict variables inside the loop
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x:x_data, y:y_data})
    if step%10 == 0:
        print(step, "Cost: ", cost_val,
                          "\nPrediction: ", hy_val)
            
# Ask my score
print("Your score will be ", sess.run(hypothesis,
                                         feed_dict={x:[[100, 70, 101]]}))
print("Other score will be ", sess.run(hypothesis,
                                         feed_dict={x:[[60, 70, 110], [90, 100, 80]]}))

0 Cost:  104393.99 
Prediction:  [[-147.66281 ]
 [-178.21295 ]
 [-174.81337 ]
 [-193.9469  ]
 [-133.40625 ]
 [-104.426186]
 [-150.64583 ]
 [-119.19075 ]
 [-171.331   ]
 [-166.96759 ]
 [-141.70546 ]
 [-141.57358 ]
 [-176.82391 ]
 [-141.99995 ]
 [-151.8833  ]
 [-184.23352 ]
 [-131.13742 ]
 [-182.65244 ]
 [-167.89764 ]
 [-150.91086 ]
 [-175.29193 ]
 [-170.7782  ]
 [-166.05278 ]
 [-140.1802  ]
 [-182.77147 ]]
10 Cost:  92.08291 
Prediction:  [[153.88326]
 [184.24527]
 [182.30681]
 [195.003  ]
 [143.01843]
 [ 99.40293]
 [140.51723]
 [ 96.68755]
 [167.44157]
 [146.86256]
 [138.80385]
 [135.034  ]
 [192.1117 ]
 [164.66829]
 [140.62431]
 [183.59183]
 [160.90938]
 [166.7772 ]
 [183.82239]
 [163.79521]
 [166.14015]
 [169.27295]
 [159.46808]
 [163.80617]
 [192.86127]]
20 Cost:  86.49009 
Prediction:  [[155.94484 ]
 [186.75008 ]
 [184.75935 ]
 [197.69318 ]
 [144.91963 ]
 [100.83738 ]
 [142.55191 ]
 [ 98.224495]
 [169.8122  ]
 [149.10318 ]
 [140.7525  ]
 [136.97467 ]
 [194.62631 ]
 [166.73302 ]
 [1

360 Cost:  68.28178 
Prediction:  [[155.28029]
 [186.77376]
 [184.30891]
 [197.81078]
 [144.64043]
 [101.66645]
 [143.31404]
 [ 99.70751]
 [170.76845]
 [151.40714]
 [141.10724]
 [137.9207 ]
 [193.55171]
 [165.02428]
 [143.63033]
 [186.67744]
 [160.74977]
 [170.3332 ]
 [184.96465]
 [164.83937]
 [169.3184 ]
 [172.20358]
 [162.24733]
 [163.7514 ]
 [195.05226]]
370 Cost:  67.817406 
Prediction:  [[155.26215 ]
 [186.77356 ]
 [184.2962  ]
 [197.81358 ]
 [144.63188 ]
 [101.688385]
 [143.33488 ]
 [ 99.748474]
 [170.7936  ]
 [151.46918 ]
 [141.11664 ]
 [137.94588 ]
 [193.5219  ]
 [164.9771  ]
 [143.65633 ]
 [186.69113 ]
 [160.69131 ]
 [170.36374 ]
 [184.93025 ]
 [164.80928 ]
 [169.34    ]
 [172.21826 ]
 [162.26132 ]
 [163.69424 ]
 [195.0408  ]]
380 Cost:  67.356766 
Prediction:  [[155.24411]
 [186.77333]
 [184.28357]
 [197.81642]
 [144.62335]
 [101.71018]
 [143.35564]
 [ 99.78931]
 [170.81862]
 [151.53093]
 [141.12599]
 [137.97092]
 [193.49222]
 [164.9301 ]
 [143.68222]
 [186.70471]
 [160.63306

670 Cost:  55.467274 
Prediction:  [[154.76196]
 [186.75778]
 [183.94044]
 [197.89557]
 [144.3781 ]
 [102.29435]
 [143.93048]
 [100.9195 ]
 [171.48845]
 [153.20311]
 [141.38275]
 [138.64671]
 [192.68315]
 [163.647  ]
 [144.39409]
 [187.06874]
 [159.03583]
 [171.23949]
 [183.96577]
 [163.96829]
 [169.95529]
 [172.62466]
 [162.66441]
 [162.09319]
 [194.71092]]
680 Cost:  55.103813 
Prediction:  [[154.74669]
 [186.75697]
 [183.92938]
 [197.89822]
 [144.36972]
 [102.31291]
 [143.94939]
 [100.95668]
 [171.5097 ]
 [153.25687]
 [141.39111]
 [138.66833]
 [192.65697]
 [163.60538]
 [144.41733]
 [187.0803 ]
 [158.9838 ]
 [171.2674 ]
 [183.93578]
 [163.94221]
 [169.97476]
 [172.63713]
 [162.6773 ]
 [162.04341]
 [194.7004 ]]
690 Cost:  54.743202 
Prediction:  [[154.73149]
 [186.75615]
 [183.91838]
 [197.90086]
 [144.36134]
 [102.33136]
 [143.96823]
 [100.99374]
 [171.53087]
 [153.31036]
 [141.39944]
 [138.68988]
 [192.63089]
 [163.56392]
 [144.4405 ]
 [187.09181]
 [158.93195]
 [171.29523]
 [183.905

1020 Cost:  44.295357 
Prediction:  [[154.27483 ]
 [186.72017 ]
 [183.58156 ]
 [197.98534 ]
 [144.08907 ]
 [102.88722 ]
 [144.55908 ]
 [102.154106]
 [172.16785 ]
 [154.94409 ]
 [141.65797 ]
 [139.34427 ]
 [191.82901 ]
 [162.2855  ]
 [145.16064 ]
 [187.43834 ]
 [157.32523 ]
 [172.17064 ]
 [182.99065 ]
 [163.12386 ]
 [170.59993 ]
 [173.02391 ]
 [163.09547 ]
 [160.47728 ]
 [194.35898 ]]
1030 Cost:  44.01874 
Prediction:  [[154.26227]
 [186.71884]
 [183.57211]
 [197.98781]
 [144.08095]
 [102.90255]
 [144.57605]
 [102.18745]
 [172.18538]
 [154.9898 ]
 [141.66533]
 [139.36249]
 [191.8064 ]
 [162.24934]
 [145.18117]
 [187.4479 ]
 [157.27953]
 [172.19589]
 [182.96492]
 [163.10168]
 [170.61726]
 [173.03426]
 [163.10721]
 [160.43472]
 [194.3494 ]]
1040 Cost:  43.74432 
Prediction:  [[154.24979 ]
 [186.71748 ]
 [183.5627  ]
 [197.99028 ]
 [144.07281 ]
 [102.917786]
 [144.59299 ]
 [102.22068 ]
 [172.20284 ]
 [155.03528 ]
 [141.67265 ]
 [139.3806  ]
 [191.78387 ]
 [162.21333 ]
 [145.20161 ]
 [187.4

1340 Cost:  36.422073 
Prediction:  [[153.90683 ]
 [186.67168 ]
 [183.29927 ]
 [198.06213 ]
 [143.833   ]
 [103.33755 ]
 [145.07773 ]
 [103.171646]
 [172.68347 ]
 [156.30646 ]
 [141.88039 ]
 [139.88477 ]
 [191.15018 ]
 [161.1974  ]
 [145.78305 ]
 [187.71921 ]
 [155.94427 ]
 [172.94463 ]
 [182.22166 ]
 [162.46304 ]
 [171.12784 ]
 [173.32863 ]
 [163.45581 ]
 [159.20555 ]
 [194.06548 ]]
1350 Cost:  36.205883 
Prediction:  [[153.89636]
 [186.66998]
 [183.29109]
 [198.06444]
 [143.82512]
 [103.35036]
 [145.09314]
 [103.20186]
 [172.69814]
 [156.34583]
 [141.88693]
 [139.90028]
 [191.13037]
 [161.16559]
 [145.80138]
 [187.7272 ]
 [155.90369]
 [172.9677 ]
 [182.19934]
 [162.44394]
 [171.14346]
 [173.33733]
 [163.46657]
 [159.16867]
 [194.05669]]
1360 Cost:  35.991325 
Prediction:  [[153.88602]
 [186.66829]
 [183.28293]
 [198.06677]
 [143.81728]
 [103.3631 ]
 [145.1085 ]
 [103.23197]
 [172.71272]
 [156.38504]
 [141.89345]
 [139.91577]
 [191.11069]
 [161.1339 ]
 [145.81967]
 [187.73515]
 [155.8

1630 Cost:  30.774687 
Prediction:  [[153.62769 ]
 [186.61885 ]
 [183.07623 ]
 [198.12753 ]
 [143.60858 ]
 [103.681076]
 [145.50615 ]
 [104.011345]
 [173.0765  ]
 [157.37749 ]
 [142.06067 ]
 [140.30554 ]
 [190.60838 ]
 [160.3244  ]
 [146.2898  ]
 [187.93356 ]
 [154.82588 ]
 [173.58812 ]
 [181.61255 ]
 [161.94348 ]
 [171.56102 ]
 [173.56226 ]
 [163.75685 ]
 [158.2001  ]
 [193.8207  ]]
1640 Cost:  30.601215 
Prediction:  [[153.61888 ]
 [186.61691 ]
 [183.06905 ]
 [198.12975 ]
 [143.60098 ]
 [103.69195 ]
 [145.52028 ]
 [104.038994]
 [173.08894 ]
 [157.41193 ]
 [142.06657 ]
 [140.319   ]
 [190.59084 ]
 [160.29605 ]
 [146.30637 ]
 [187.94034 ]
 [154.7894  ]
 [173.6094  ]
 [181.59293 ]
 [161.9268  ]
 [171.57524 ]
 [173.56966 ]
 [163.76685 ]
 [158.16772 ]
 [193.8126  ]]
1650 Cost:  30.429087 
Prediction:  [[153.61014 ]
 [186.61494 ]
 [183.06189 ]
 [198.13193 ]
 [143.59338 ]
 [103.702736]
 [145.53433 ]
 [104.06656 ]
 [173.10129 ]
 [157.44617 ]
 [142.07243 ]
 [140.33237 ]
 [190.57338 ]
 [160.26

1950 Cost:  25.82235 
Prediction:  [[153.37096 ]
 [186.55322 ]
 [182.86159 ]
 [198.19533 ]
 [143.3701  ]
 [103.999115]
 [145.93741 ]
 [104.85579 ]
 [173.44008 ]
 [158.40271 ]
 [142.23882 ]
 [140.70409 ]
 [190.08153 ]
 [159.47081 ]
 [146.79271 ]
 [188.13213 ]
 [153.7219  ]
 [174.24    ]
 [181.02489 ]
 [161.4462  ]
 [171.99423 ]
 [173.77979 ]
 [164.06328 ]
 [157.23201 ]
 [193.5721  ]]
1960 Cost:  25.685875 
Prediction:  [[153.36371]
 [186.55106]
 [182.85538]
 [198.19739]
 [143.36282]
 [104.00812]
 [145.95023]
 [104.88088]
 [173.45038]
 [158.43234]
 [142.24406]
 [140.71553]
 [190.06616]
 [159.44585]
 [146.80756]
 [188.13776]
 [153.68942]
 [174.25946]
 [181.00781]
 [161.43182]
 [172.00706]
 [173.78598]
 [164.07245]
 [157.20395]
 [193.56468]]
1970 Cost:  25.550426 
Prediction:  [[153.3565 ]
 [186.5489 ]
 [182.84917]
 [198.19942]
 [143.35553]
 [104.01709]
 [145.96301]
 [104.90591]
 [173.4606 ]
 [158.46182]
 [142.24928]
 [140.72691]
 [190.05086]
 [159.42096]
 [146.82234]
 [188.14336]
 [153.65

In [32]:
sess.close()