In [0]:
import tensorflow as tf
import numpy as np

### Non_normalized inputs

In [0]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [0]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())

        for step in range(101):
            cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                                         feed_dict={X: x_data, Y: y_data})
            print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

Instructions for updating:
Colocations handled automatically by placer.
0 Cost:  417078540000.0 
Prediction:
 [[-454979.03]
 [-915951.25]
 [-720540.06]
 [-505084.72]
 [-595277.06]
 [-600285.4 ]
 [-550181.4 ]
 [-700490.06]]
1 Cost:  4.58236e+26 
Prediction:
 [[1.5099964e+13]
 [3.0397776e+13]
 [2.3912834e+13]
 [1.6762770e+13]
 [1.9755820e+13]
 [1.9922101e+13]
 [1.8259294e+13]
 [2.3247712e+13]]
2 Cost:  inf 
Prediction:
 [[-5.00508706e+20]
 [-1.00757536e+21]
 [-7.92623190e+20]
 [-5.55624638e+20]
 [-6.54833308e+20]
 [-6.60344940e+20]
 [-6.05228973e+20]
 [-7.70576803e+20]]
3 Cost:  inf 
Prediction:
 [[1.6590036e+28]
 [3.3397445e+28]
 [2.6272565e+28]
 [1.8416928e+28]
 [2.1705335e+28]
 [2.1888022e+28]
 [2.0061132e+28]
 [2.5541807e+28]]
4 Cost:  inf 
Prediction:
 [[-5.49899185e+35]
 [-1.10700346e+36]
 [-8.70839676e+35]
 [-6.10453983e+35]
 [-7.19452642e+35]
 [-7.25508130e+35]
 [-6.64953332e+35]
 [-8.46617725e+35]]
5 Cost:  inf 
Prediction:
 [[inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf

### Need to do normalization
#### from sklearn.preprocessing import MinMaxScaler

In [0]:
from sklearn.preprocessing import MinMaxScaler

#### MinMaxScaler for normalization

In [0]:
# def MinMaxScaler(data):
#     numerator = data - np.min(data, 0)
#     denominator = np.max(data, 0) - np.min(data, 0)
#     # noise term prevents the zero division
#     return numerator / (denominator + 1e-7)

xy = MinMaxScaler().fit(xy).transform(xy)
print(xy)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

[[1.         1.         0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881783 0.83755792]
 [0.54412549 0.50274824 0.57608696 0.60646801 0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.4258239  0.30434783 0.58504805 0.42624401]
 [0.49556179 0.4258239  0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [0]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())

        for step in range(101):
            cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                                         feed_dict={X: x_data, Y: y_data})
            print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  3.4385576 
Prediction:
 [[-1.8153298 ]
 [-2.2788095 ]
 [-1.4836807 ]
 [-0.5715175 ]
 [-1.0962427 ]
 [-0.8759355 ]
 [-0.06291693]
 [ 0.01290894]]
1 Cost:  3.438326 
Prediction:
 [[-1.8152392 ]
 [-2.278723  ]
 [-1.4836092 ]
 [-0.57146305]
 [-1.0961773 ]
 [-0.87587255]
 [-0.06287664]
 [ 0.0129481 ]]
2 Cost:  3.4380937 
Prediction:
 [[-1.8151486 ]
 [-2.2786362 ]
 [-1.4835377 ]
 [-0.57140857]
 [-1.096112  ]
 [-0.8758097 ]
 [-0.06283653]
 [ 0.01298726]]
3 Cost:  3.4378617 
Prediction:
 [[-1.815058  ]
 [-2.2785494 ]
 [-1.4834664 ]
 [-0.5713542 ]
 [-1.0960467 ]
 [-0.8757469 ]
 [-0.06279629]
 [ 0.01302642]]
4 Cost:  3.4376292 
Prediction:
 [[-1.8149674 ]
 [-2.278463  ]
 [-1.4833946 ]
 [-0.57129985]
 [-1.0959814 ]
 [-0.87568384]
 [-0.06275606]
 [ 0.01306564]]
5 Cost:  3.4373975 
Prediction:
 [[-1.8148768 ]
 [-2.278376  ]
 [-1.4833231 ]
 [-0.5712454 ]
 [-1.095916  ]
 [-0.87562114]
 [-0.06271595]
 [ 0.0131048 ]]
6 Cost:  3.4371655 
Prediction:
 [[-1.8147862 ]
 [-2.2782896 ]
 [-1.4832516 ]

In [24]:
"""

tensorflow as normalization function
tf.nn.batch_normalization(x, mean, variance, offset, scale, variance_epsilon, name=None)
x: Input Tensor of arbitrary dimensionality.
mean: A mean Tensor.
variance: A variance Tensor.
offset: An offset Tensor, often denoted \(\beta\) in equations, or None. If present, will be added to the normalized tensor.
scale: A scale Tensor, often denoted \(\gamma\) in equations, or None. If present, the scale is applied to the normalized tensor.
variance_epsilon: A small float number to avoid dividing by 0.
name: A name for this operation (optional).

"""



def MinMaxScaler2(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)


import tensorflow as tf
import numpy as np
from sklearn.preprocessing import MinMaxScaler

data = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

x = tf.placeholder(tf.float32, [None, 5])
W = tf.Variable(tf.random_normal([5, 1]), name='weight')
print(W.shape)
b = tf.Variable(tf.random_normal([1]), name='bias')

y = tf.matmul(x, W) + b

mean, variance = tf.nn.moments(y, axes=[0])
scale = tf.Variable(tf.ones([1]))
beta = tf.Variable(tf.zeros([1]))
epsilon = 1e-3


BN = tf.nn.batch_normalization(data, mean, variance, None, None, epsilon)
print(BN.shape)

(5, 1)
(8, 5)


In [25]:
def normalization(data):
  mean = np.mean(data)
  variance = np.var(data)
  
  print("mean:", mean)
  print("variance:",variance)
  
  return (data - mean) / np.sqrt(variance**2 + 1e-4)

data = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
normalization(data)


data = np.random.normal(0, 1, 25).reshape(-1, 5)
print(data, "\n")
print(normalization(data))
print(MinMaxScaler2(data))

data = MinMaxScaler().fit(data).transform(data)
print(data)

mean: 252275.77559655003
variance: 267820592634.72247
[[-1.60235511e+00 -1.49428601e+00  8.28941399e-04 -3.59892323e-01
   8.47913270e-02]
 [-4.20168231e-01  7.44450521e-01 -5.87524795e-01  9.25248426e-01
  -4.51453577e-01]
 [ 1.99738413e+00  2.07061529e+00  9.69783647e-01  8.37881077e-01
  -9.43005456e-01]
 [-9.90967216e-03 -1.89058110e-01 -1.68581952e+00  1.42683092e+00
  -9.64709732e-01]
 [ 3.32121876e-01  9.82039278e-01 -1.92135106e+00  1.55540553e+00
  -8.43877603e-01]] 

mean: 0.01815879070428815
variance: 1.2646222832470273
[[-1.28138122 -1.19592825 -0.01370315 -0.29893455  0.05268803]
 [-0.34659623  0.57429719 -0.47892929  0.71725865 -0.37133434]
 [ 1.56502339  1.62292912  0.75247378  0.64817509 -0.76001681]
 [-0.02219444 -0.16385163 -1.34737863  1.11387258 -0.77717893]
 [ 0.24825853  0.76216461 -1.53361936  1.21553977 -0.68163392]]
[[0.         0.         0.66485312 0.         0.9999999 ]
 [0.32840902 0.62799396 0.46135042 0.67098738 0.48904773]
 [0.99999997 0.99999997 0.99999