In [1]:
import numpy as np
import tensorflow as tf

In [2]:
x_data = [[1, 2, 1], [1, 3, 2], [1, 3, 4], [1, 5, 5], [1, 7, 5], [1, 2, 5], [1, 6, 6], [1, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

x_test = [[2, 1, 1], [3, 1, 2], [3, 3, 4]]
y_test = [[0, 0, 1], [0, 0, 1], [0, 0, 1]]

In [8]:
x = tf.placeholder(tf.float32, [None, 3])
y = tf.placeholder(tf.float32, [None, 3])

W = tf.Variable(tf.random_normal([3, 3]), name = "weight")
b = tf.Variable(tf.random_normal([3]), name = "bias")

hypothesis = tf.nn.softmax(tf.matmul(x, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(y * tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(0.1).minimize(cost)

# Correct prediction Test Model
prediction = tf.argmax(hypothesis, axis = 1)
is_correct = tf.equal(prediction, tf.argmax(y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch the graph
with tf.Session() as sess:
    # Initialize Tensorflow's Variables
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, w_val, _ = sess.run([cost, W, optimizer],
                                     feed_dict={x:x_data, y:y_data})
        print("Step: ", step, "\nCost: ", cost_val, "\nWeight:\n", w_val)

    print()    
    # Predict
    print("Prediction: ", sess.run(prediction, feed_dict={x:x_test}))
    # Calculate the accuray
    print("Accuracy: ", sess.run(accuracy, feed_dict={x:x_test, y:y_test}))

Step:  0 
Cost:  3.8388124 
Weight:
 [[-0.3054122   1.3665749   1.1226267 ]
 [ 0.17024714  0.4969121   0.2585044 ]
 [-0.872145   -0.56067497 -0.6920828 ]]
Step:  1 
Cost:  1.9261451 
Weight:
 [[-0.28347057  1.3218416   1.1454183 ]
 [ 0.32391798  0.29349303  0.30825257]
 [-0.71805084 -0.75031173 -0.65654016]]
Step:  2 
Cost:  1.1582062 
Weight:
 [[-0.2772855   1.3261275   1.1349472 ]
 [ 0.40373212  0.32948634  0.19244513]
 [-0.6376065  -0.7010244  -0.7862718 ]]
Step:  3 
Cost:  1.0238502 
Weight:
 [[-0.28967637  1.3176568   1.1558088 ]
 [ 0.38734925  0.30580014  0.23251423]
 [-0.6522642  -0.7127573  -0.75988126]]
Step:  4 
Cost:  0.99298024 
Weight:
 [[-0.2991174   1.3132756   1.169631  ]
 [ 0.38491592  0.30055118  0.24019653]
 [-0.6528316  -0.7060849  -0.7659862 ]]
Step:  5 
Cost:  0.98558176 
Weight:
 [[-0.3076105   1.308829    1.1825707 ]
 [ 0.387048    0.29470676  0.24390882]
 [-0.6488625  -0.7003613  -0.77567893]]
Step:  6 
Cost:  0.9785447 
Weight:
 [[-0.3164757   1.3047976   1.19

Step:  139 
Cost:  0.63842714 
Weight:
 [[-1.1129664   1.0305372   2.2662177 ]
 [ 0.4382403   0.23603606  0.25138754]
 [-0.37581435 -0.49773657 -1.2513515 ]]
Step:  140 
Cost:  0.637408 
Weight:
 [[-1.1174717   1.0298419   2.2714183 ]
 [ 0.4384985   0.23645195  0.2507134 ]
 [-0.37427244 -0.49766898 -1.252961  ]]
Step:  141 
Cost:  0.63639677 
Weight:
 [[-1.1219648   1.029158    2.2765954 ]
 [ 0.43875477  0.23686635  0.25004274]
 [-0.3727339  -0.49760485 -1.2545637 ]]
Step:  142 
Cost:  0.6353933 
Weight:
 [[-1.1264459   1.0284853   2.281749  ]
 [ 0.4390092   0.23727912  0.24937555]
 [-0.37119856 -0.49754417 -1.2561597 ]]
Step:  143 
Cost:  0.6343974 
Weight:
 [[-1.130915    1.0278237   2.2868798 ]
 [ 0.43926167  0.2376903   0.2487119 ]
 [-0.36966652 -0.49748683 -1.2577491 ]]
Step:  144 
Cost:  0.633409 
Weight:
 [[-1.1353724   1.027173    2.2919877 ]
 [ 0.43951225  0.23809981  0.24805179]
 [-0.36813763 -0.4974328  -1.2593321 ]]
Step:  145 
Cost:  0.63242817 
Weight:
 [[-1.1398181   1.0